services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8080:8000"
    volumes:
      - .:/var/www
    networks:
      - app-network
    command: >
      sh -c "
      composer install &&
      until mysqladmin ping -h mysql --silent; do echo 'Aguardando MySQL...'; sleep 5; done &&
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=8000
      "
  
  frontend:
    build:
      context: .././frontend_react  # Caminho para o diretório frontend_react
    container_name: frontend-react
    ports:
      - "3000:3000"  # Expor a porta 3000 para acessar o frontend React
    volumes:
      - .././frontend_react:/usr/src/app  # Sincroniza o código local com o contêiner
    networks:
      - app-network
    command: >
      sh -c "
      npm install &&
      npm start
      "  # Instalar dependências e rodar o servidor de desenvolvimento React
  
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbredesocial
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge